image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE/frontend:latest ./src/frontend
    - docker build -t $CI_REGISTRY_IMAGE/backend:latest ./src/backend
    - docker push $CI_REGISTRY_IMAGE/frontend:latest
    - docker push $CI_REGISTRY_IMAGE/backend:latest

deploy:
  stage: deploy
  only:
    - main
  script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh -o StrictHostKeyChecking=no $SWARM_SERVER_USER@$SWARM_SERVER_IP 'cd ~/mini-hospital-booking && git pull && ./swarm-deploy.sh'
