version: '3.8'

services:
  backend:
    build: ./src/backend
    ports:
      - "5000:5000"
    networks:
      - appnet

  frontend:
    build: ./src/frontend
    ports:
      - "3000:80"
    networks:
      - appnet

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: hospital
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - appnet

networks:
  appnet:

volumes:
  db_data:
